name: Artifacts
on: [push]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: amd64
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc-latest
      - name: Build
        run: |
          dub -b release
      - name: Tests
        run: |
          dub -b release -- install -v
          dub -b release -- install ldc2-master -v
          dub -b release -- list -v
          dub -b release -- uninstall ldc2-1.40.0 -v
          dub -b release -- list -v
          dub -b release -- run -v -- --version
      - uses: actions/upload-artifact@v4
        with:
          name: ldcup-${{ matrix.os }}-${{ matrix.arch }}
          path: bin

  freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y dub ldc
          run: |
            dub -b release
            dub -b release -- install -v
            dub -b release -- install ldc2-master -v
            dub -b release -- list -v
            dub -b release -- uninstall ldc2-1.40.0 -v
            dub -b release -- list -v
            dub -b release -- run -v -- --version
      - uses: actions/upload-artifact@v4
        with:
          name: ldcup-freebsd-14.2-amd64
          path: bin
