name: Artifacts
on: [push, workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        arch: [x86_64]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc-latest
      - run: |
          dub -b release
      - if: ${{ matrix.os == 'ubuntu-latest'  }}
        uses: actions/upload-artifact@v4
        with:
          name: ldcup-${{ matrix.os }}-${{ matrix.arch }}
          path: bin